### ISSUE TITLE
Undefined variable in one of the FIXME comments

### ISSUE THREAD

**Issue by Poikilos** [bobjacobsen/PythonOlcbNode#33]
I'm not sure which variable should be sliced as noted in comment. The comment is added in https://github.com/bobjacobsen/PythonOlcbNode/pull/32 but the issue predates the PR.

**Comment by bobjacobsen** [comment]
Fixed by #37.  References needed to be to `self` variables.

**Comment by Poikilos** [comment]
You can still see it (issue #33) with either VSCode, or on CLI (Terminal) with:
```
python -m pip install flake8
cd PythonOlcbNode
python -m flake8 --ignore=E203,E226,E701,E202,E222,E221,W503,E241 --per-file-ignores="test_all.py:F401,E402,F403"
```
- The `--ignore` arg value mimics the settings in the vscode project file which ignore your spacing styles which are not causing actual issues nor seem to cause readability issues.
- The `--per-file-ignores` arg value ignores several instances of "E402 module level import not at top of file" and "...import *' used; unable to detect undefined name" which also don't cause actual issues (could prevent a linter such as flake8 or pylance from identifying undefined names properly but aren't relevant in this case since they are only importing tests).

**Comment by Poikilos** [comment]
Fixed in https://github.com/bobjacobsen/PythonOlcbNode/pull/37/commits/af9ebf350c7774cfd66c1ce6113436f09cc92e8b
